#---------------------------------------------------------------
# Theme version infromation
#---------------------------------------------------------------
version: 1.0

#---------------------------------------------------------------
# Build setting
#---------------------------------------------------------------
gems: [jekyll-paginate]
# Config sass build output by sass_dir
# Config sass output is compressed or not

safe: false

#
sass:
    sass_dir: /assets/stylesheet
    style: :compressed


#---------------------------------------------------------------
# Site infromation setting
#---------------------------------------------------------------

# Site
## You can create a locale setting at _locales and name *.yml
title: "数字编程"
description: "数字编程的博客"
keywords: "intcpu 数字编程"
locale: "zh_CN"

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and baseurl as '/child/'
url: ""
baseurl: ""
permalink: /:year/:month/:day/:title

# Pagination
## Set per_page to 0 to disable pagination
paginate: 1
paginate_path: "/page:num/"

# Writing
highlighter: 'rouge'
kramdown:
  input:  GFM
  syntax_highlighter: syntax_highlighter_opts
  coderay:
    line_numbers:  nil

# RSS
rss:
  path: "/feed.xml"
  icon: "rss"


#---------------------------------------------------------------
# Authour infromation setting
#---------------------------------------------------------------

# Author
author:
  name: "数字编程"
  avatar: "http://i.imgur.com/JAtG4dq.png"
  motto: "这是一个技术，在整理学习笔记"

# Socials
## If you want the social show,place sure the social no comment
## The socials icon base font-awesome,you can learn more on http://fontawesome.io/icons/
socials:
    - name: "weibo"
      url: "http://www.weibo.com/intcpu"
      icon: "weibo"
    - name: "github"
      url: "https://github.com/intcpu"
      icon: "github"
    - name: "facebook"
      url: "https://www.facebook.com/intcpu"
      icon: "facebook"




#---------------------------------------------------------------
# Site comment setting
#---------------------------------------------------------------

comment:
  enable: true

# duoshuo
duoshuo:
  enable: false
  short_name: "your duoshuo short_name"

# disqus
disqus:
  enable: true
  short_name: "zhuanye"

#---------------------------------------------------------------
# Site share setting
#---------------------------------------------------------------
duoshuo_share:
    enable: false

#---------------------------------------------------------------
# Site analysis setting
#---------------------------------------------------------------
# Baidu analysis
baidu_analysis:
  enable: false
  token: "your baidu analysis token"

# Google analysis
google_analysus:
  enable: false
  token: "your google analysis token"
